"""add disclosures table

Revision ID: 9181478c6ec0
Revises: 8c2f8cc1babc
Create Date: 2026-02-17 05:51:13.145943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9181478c6ec0'
down_revision: Union[str, None] = '8c2f8cc1babc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='사용자명'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='해시된 비밀번호'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='역할 (admin/analyst/viewer)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='기업 ID'),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='알림 유형'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='알림 제목'),
    sa.Column('message', sa.Text(), nullable=True, comment='알림 내용'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='읽음 여부'),
    sa.Column('reference_id', sa.Integer(), nullable=True, comment='참조 레코드 ID'),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment='참조 유형 (disclosure/deal/...)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_company_id'), 'alert_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_alert_history_is_read'), 'alert_history', ['is_read'], unique=False)
    op.create_index(op.f('ix_alert_history_user_id'), 'alert_history', ['user_id'], unique=False)
    op.create_table('classified_sanctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='기업 ID'),
    sa.Column('corp_code', sa.String(length=20), nullable=False, comment='DART 고유번호'),
    sa.Column('sanctions_type', sa.String(length=200), nullable=False, comment='제재유형'),
    sa.Column('sanctions_detail', sa.Text(), nullable=True, comment='제재내용'),
    sa.Column('sanctions_date', sa.String(length=20), nullable=True, comment='제재일자'),
    sa.Column('sanctions_agency', sa.String(length=100), nullable=True, comment='제재기관'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='경중 등급 (caution/warning/critical)'),
    sa.Column('severity_reason', sa.Text(), nullable=True, comment='경중 분류 근거'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='제재 유형 분류 (administrative/disclosure/fraud/embezzlement/other)'),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True, comment='분류 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classified_sanctions_company_id'), 'classified_sanctions', ['company_id'], unique=False)
    op.create_index(op.f('ix_classified_sanctions_corp_code'), 'classified_sanctions', ['corp_code'], unique=False)
    op.create_index(op.f('ix_classified_sanctions_severity'), 'classified_sanctions', ['severity'], unique=False)
    op.create_table('disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='기업 ID'),
    sa.Column('corp_code', sa.String(length=20), nullable=False, comment='DART 고유번호'),
    sa.Column('corp_name', sa.String(length=300), nullable=True, comment='종목명'),
    sa.Column('corp_cls', sa.String(length=5), nullable=True, comment='법인구분'),
    sa.Column('report_nm', sa.String(length=500), nullable=False, comment='보고서명'),
    sa.Column('rcept_no', sa.String(length=20), nullable=False, comment='접수번호'),
    sa.Column('rcept_dt', sa.String(length=10), nullable=True, comment='접수일자 (YYYYMMDD)'),
    sa.Column('flr_nm', sa.String(length=200), nullable=True, comment='공시 제출인명'),
    sa.Column('rm', sa.Text(), nullable=True, comment='비고'),
    sa.Column('dart_viewer_url', sa.String(length=500), nullable=False, comment='DART 뷰어 URL'),
    sa.Column('dart_pdf_url', sa.String(length=500), nullable=True, comment='DART PDF 다운로드 URL'),
    sa.Column('disclosure_type', sa.String(length=50), nullable=True, comment='공시 유형 (annual_report/audit_report/...)'),
    sa.Column('kofia_url', sa.String(length=500), nullable=True, comment='KOFIA 공시 원문 URL'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='데이터 출처 (dart/kofia)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disclosures_company_id'), 'disclosures', ['company_id'], unique=False)
    op.create_index(op.f('ix_disclosures_corp_code'), 'disclosures', ['corp_code'], unique=False)
    op.create_index(op.f('ix_disclosures_disclosure_type'), 'disclosures', ['disclosure_type'], unique=False)
    op.create_index(op.f('ix_disclosures_rcept_no'), 'disclosures', ['rcept_no'], unique=True)
    op.create_index(op.f('ix_disclosures_report_nm'), 'disclosures', ['report_nm'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='기업 ID'),
    sa.Column('alert_types', sa.Text(), nullable=True, comment='알림 유형 (JSON array)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company')
    )
    op.create_index(op.f('ix_watchlists_company_id'), 'watchlists', ['company_id'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('manager_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(length=100), nullable=False, comment='심사역 이름'),
    sa.Column('from_company_id', sa.Integer(), nullable=True, comment='이전 소속 기업 ID'),
    sa.Column('from_company_name', sa.String(length=300), nullable=True, comment='이전 소속 기업명'),
    sa.Column('from_fund_id', sa.Integer(), nullable=True, comment='이전 소속 펀드 ID'),
    sa.Column('to_company_id', sa.Integer(), nullable=True, comment='새 소속 기업 ID'),
    sa.Column('to_company_name', sa.String(length=300), nullable=True, comment='새 소속 기업명'),
    sa.Column('to_fund_id', sa.Integer(), nullable=True, comment='새 소속 펀드 ID'),
    sa.Column('movement_type', sa.String(length=20), nullable=False, comment='이동 유형 (transfer/resignation/appointment)'),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False, comment='감지 일시'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='감지 출처 (kofia/news)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_fund_id'], ['funds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_fund_id'], ['funds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_movements_from_company_id'), 'manager_movements', ['from_company_id'], unique=False)
    op.create_index(op.f('ix_manager_movements_manager_name'), 'manager_movements', ['manager_name'], unique=False)
    op.create_index(op.f('ix_manager_movements_movement_type'), 'manager_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_manager_movements_to_company_id'), 'manager_movements', ['to_company_id'], unique=False)
    op.create_table('portfolio_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_company_id', sa.Integer(), nullable=False, comment='투자사(GP) 기업 ID'),
    sa.Column('target_company_name', sa.String(length=300), nullable=False, comment='피투자사명'),
    sa.Column('target_company_id', sa.Integer(), nullable=True, comment='피투자사 기업 ID (식별된 경우)'),
    sa.Column('deal_id', sa.Integer(), nullable=True, comment='관련 딜 ID'),
    sa.Column('survival_status', sa.String(length=20), nullable=False, comment='생존 상태 (active/audit_missing/dissolved/unicorn/unknown)'),
    sa.Column('last_audit_date', sa.Date(), nullable=True, comment='최근 감사보고서 접수일'),
    sa.Column('last_audit_rcept_no', sa.String(length=20), nullable=True, comment='최근 감사보고서 접수번호'),
    sa.Column('dissolution_date', sa.Date(), nullable=True, comment='해산/폐업 공시일'),
    sa.Column('dissolution_rcept_no', sa.String(length=20), nullable=True, comment='해산/폐업 공시 접수번호'),
    sa.Column('estimated_valuation', sa.Numeric(precision=20, scale=0), nullable=True, comment='추정 기업가치 (원)'),
    sa.Column('is_unicorn', sa.Boolean(), nullable=False, comment='유니콘 여부 (기업가치 1조원 이상)'),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 생존 확인 시각'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investor_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_companies_deal_id'), 'portfolio_companies', ['deal_id'], unique=False)
    op.create_index(op.f('ix_portfolio_companies_investor_company_id'), 'portfolio_companies', ['investor_company_id'], unique=False)
    op.create_index(op.f('ix_portfolio_companies_survival_status'), 'portfolio_companies', ['survival_status'], unique=False)
    op.create_index(op.f('ix_portfolio_companies_target_company_id'), 'portfolio_companies', ['target_company_id'], unique=False)
    op.create_index(op.f('ix_portfolio_companies_target_company_name'), 'portfolio_companies', ['target_company_name'], unique=False)
    op.add_column('fund_managers', sa.Column('specialty_sectors', sa.Text(), nullable=True, comment='전문 섹터 (JSON)'))
    op.add_column('fund_managers', sa.Column('profile_summary', sa.Text(), nullable=True, comment='프로필 요약'))
    op.add_column('fund_managers', sa.Column('total_deals_involved', sa.Integer(), nullable=False, comment='관여 딜 수'))
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index('ix_reputation_history_company_recorded', 'reputation_history', ['company_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reputation_history_company_recorded', table_name='reputation_history')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_column('fund_managers', 'total_deals_involved')
    op.drop_column('fund_managers', 'profile_summary')
    op.drop_column('fund_managers', 'specialty_sectors')
    op.drop_index(op.f('ix_portfolio_companies_target_company_name'), table_name='portfolio_companies')
    op.drop_index(op.f('ix_portfolio_companies_target_company_id'), table_name='portfolio_companies')
    op.drop_index(op.f('ix_portfolio_companies_survival_status'), table_name='portfolio_companies')
    op.drop_index(op.f('ix_portfolio_companies_investor_company_id'), table_name='portfolio_companies')
    op.drop_index(op.f('ix_portfolio_companies_deal_id'), table_name='portfolio_companies')
    op.drop_table('portfolio_companies')
    op.drop_index(op.f('ix_manager_movements_to_company_id'), table_name='manager_movements')
    op.drop_index(op.f('ix_manager_movements_movement_type'), table_name='manager_movements')
    op.drop_index(op.f('ix_manager_movements_manager_name'), table_name='manager_movements')
    op.drop_index(op.f('ix_manager_movements_from_company_id'), table_name='manager_movements')
    op.drop_table('manager_movements')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_company_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_disclosures_report_nm'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_rcept_no'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_disclosure_type'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_corp_code'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_company_id'), table_name='disclosures')
    op.drop_table('disclosures')
    op.drop_index(op.f('ix_classified_sanctions_severity'), table_name='classified_sanctions')
    op.drop_index(op.f('ix_classified_sanctions_corp_code'), table_name='classified_sanctions')
    op.drop_index(op.f('ix_classified_sanctions_company_id'), table_name='classified_sanctions')
    op.drop_table('classified_sanctions')
    op.drop_index(op.f('ix_alert_history_user_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_is_read'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_company_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
