"""initial tables

Revision ID: df25553292c9
Revises: 
Create Date: 2026-02-09 15:21:01.347815

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df25553292c9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corp_code', sa.String(length=20), nullable=False, comment='DART 고유번호'),
    sa.Column('corp_name', sa.String(length=300), nullable=False, comment='정식명칭'),
    sa.Column('corp_name_eng', sa.String(length=300), nullable=True, comment='영문명칭'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='종목명'),
    sa.Column('stock_code', sa.String(length=20), nullable=True, comment='종목코드'),
    sa.Column('ceo_nm', sa.String(length=100), nullable=True, comment='대표자명'),
    sa.Column('corp_cls', sa.String(length=5), nullable=True, comment='법인구분 (Y:유가, K:코스닥, N:코넥스, E:기타)'),
    sa.Column('jurir_no', sa.String(length=20), nullable=True, comment='법인등록번호'),
    sa.Column('bizr_no', sa.String(length=20), nullable=True, comment='사업자등록번호'),
    sa.Column('adres', sa.Text(), nullable=True, comment='주소'),
    sa.Column('hm_url', sa.String(length=500), nullable=True, comment='홈페이지'),
    sa.Column('ir_url', sa.String(length=500), nullable=True, comment='IR 홈페이지'),
    sa.Column('phn_no', sa.String(length=50), nullable=True, comment='전화번호'),
    sa.Column('fax_no', sa.String(length=50), nullable=True, comment='팩스번호'),
    sa.Column('induty_code', sa.String(length=20), nullable=True, comment='업종코드'),
    sa.Column('est_dt', sa.String(length=10), nullable=True, comment='설립일 (YYYYMMDD)'),
    sa.Column('acc_mt', sa.String(length=5), nullable=True, comment='결산월'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurir_no')
    )
    op.create_index(op.f('ix_companies_corp_code'), 'companies', ['corp_code'], unique=True)
    op.create_index(op.f('ix_companies_corp_name'), 'companies', ['corp_name'], unique=False)
    op.create_index(op.f('ix_companies_stock_code'), 'companies', ['stock_code'], unique=False)
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=300), nullable=False, comment='별칭 (약칭, 줄임말 등)'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='정규 기업 ID'),
    sa.Column('is_manual', sa.Boolean(), nullable=False, comment='수동 등록 여부 (False=자동 생성)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name', 'company_id', name='uq_alias_company')
    )
    op.create_index(op.f('ix_company_aliases_alias_name'), 'company_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_code', sa.String(length=50), nullable=False, comment='펀드 표준코드'),
    sa.Column('fund_name', sa.String(length=300), nullable=False, comment='펀드명'),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='운용사 기업 ID'),
    sa.Column('fund_type', sa.String(length=20), nullable=False, comment='펀드 유형 (blind/project)'),
    sa.Column('fund_category', sa.String(length=50), nullable=True, comment='펀드 분류 (VC/PEF)'),
    sa.Column('company_name', sa.String(length=200), nullable=False, comment='운용사명'),
    sa.Column('company_code', sa.String(length=50), nullable=True, comment='운용사 코드'),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=0), nullable=True, comment='설정액 (원)'),
    sa.Column('management_fee_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='운용보수율 (%)'),
    sa.Column('performance_fee_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='성과보수율 (%)'),
    sa.Column('established_date', sa.Date(), nullable=True, comment='설정일'),
    sa.Column('maturity_date', sa.Date(), nullable=True, comment='만기일'),
    sa.Column('vintage_year', sa.Integer(), nullable=True, comment='빈티지 연도'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('is_maturity_alert', sa.Boolean(), nullable=False, comment='회수 집중 구간 여부 (7~10년차)'),
    sa.Column('description', sa.Text(), nullable=True, comment='펀드 설명'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='출처 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_company_id'), 'funds', ['company_id'], unique=False)
    op.create_index(op.f('ix_funds_company_name'), 'funds', ['company_name'], unique=False)
    op.create_index(op.f('ix_funds_fund_code'), 'funds', ['fund_code'], unique=True)
    op.create_index(op.f('ix_funds_fund_name'), 'funds', ['fund_name'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='기사 제목'),
    sa.Column('content', sa.Text(), nullable=True, comment='기사 본문'),
    sa.Column('summary', sa.Text(), nullable=True, comment='기사 요약'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='출처 (platum, dealsite 등)'),
    sa.Column('author', sa.String(length=100), nullable=True, comment='저자'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='발행일시'),
    sa.Column('url', sa.String(length=1000), nullable=False, comment='기사 URL'),
    sa.Column('url_hash', sa.String(length=64), nullable=False, comment='URL SHA256 해시 (중복 감지)'),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='감성 점수 (-1.0 ~ 1.0)'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='키워드 (JSON)'),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='관련 기업 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_company_id'), 'news_articles', ['company_id'], unique=False)
    op.create_index(op.f('ix_news_articles_source'), 'news_articles', ['source'], unique=False)
    op.create_index(op.f('ix_news_articles_title'), 'news_articles', ['title'], unique=False)
    op.create_index(op.f('ix_news_articles_url_hash'), 'news_articles', ['url_hash'], unique=False)
    op.create_table('reits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reits_code', sa.String(length=50), nullable=False, comment='리츠 코드'),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='관리 기업 ID'),
    sa.Column('reits_name', sa.String(length=300), nullable=False, comment='리츠명'),
    sa.Column('reits_type', sa.String(length=20), nullable=False, comment='리츠 유형 (self_managed/entrusted)'),
    sa.Column('management_company', sa.String(length=200), nullable=True, comment='자산관리회사명'),
    sa.Column('establishment_date', sa.Date(), nullable=True, comment='설립인가일'),
    sa.Column('listing_date', sa.Date(), nullable=True, comment='상장일'),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=0), nullable=True, comment='총자산 (백만원)'),
    sa.Column('real_estate_amount', sa.Numeric(precision=20, scale=0), nullable=True, comment='부동산 자산액 (백만원)'),
    sa.Column('real_estate_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='부동산 비율 (%)'),
    sa.Column('has_asset_ratio_warning', sa.Boolean(), nullable=False, comment='부동산 70% 미달 경고'),
    sa.Column('dividend_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='배당수익률 (%)'),
    sa.Column('dividend_payout_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='배당성향 (배당금/당기순이익, %)'),
    sa.Column('net_income', sa.Numeric(precision=20, scale=0), nullable=True, comment='당기순이익 (백만원)'),
    sa.Column('total_dividend', sa.Numeric(precision=20, scale=0), nullable=True, comment='배당금 총액 (백만원)'),
    sa.Column('employee_count', sa.Integer(), nullable=True, comment='임직원 수'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (authorized/operating/dissolved)'),
    sa.Column('is_listed', sa.Boolean(), nullable=False, comment='상장 여부'),
    sa.Column('description', sa.Text(), nullable=True, comment='리츠 설명'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='출처 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reits_company_id'), 'reits', ['company_id'], unique=False)
    op.create_index(op.f('ix_reits_reits_code'), 'reits', ['reits_code'], unique=True)
    op.create_index(op.f('ix_reits_reits_name'), 'reits', ['reits_name'], unique=False)
    op.create_table('reputation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='기업 ID'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='해당 시점 총합 평판 지수'),
    sa.Column('status_tag', sa.String(length=20), nullable=False, comment='해당 시점 상태 태그'),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='트렌드 점수'),
    sa.Column('news_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='뉴스 점수'),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='성과 점수'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='기록 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_history_company_id'), 'reputation_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_reputation_history_recorded_at'), 'reputation_history', ['recorded_at'], unique=False)
    op.create_table('reputation_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='기업 ID'),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='트렌드 점수 (0.0~1.0)'),
    sa.Column('news_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='뉴스 평판 점수 (-1.0~1.0)'),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='성과 지표 점수 (0.0~1.0)'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='총합 평판 지수 (0.0~1.0)'),
    sa.Column('status_tag', sa.String(length=20), nullable=False, comment='상태 태그 (rising/stable/risk)'),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False, comment='점수 산출 시각'),
    sa.Column('news_count', sa.Integer(), nullable=False, comment='분석 뉴스 수'),
    sa.Column('exit_count', sa.Integer(), nullable=False, comment='1년 내 엑시트 횟수'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_scores_company_id'), 'reputation_scores', ['company_id'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='투자사(GP) 기업 ID'),
    sa.Column('target_company', sa.String(length=300), nullable=False, comment='피투자사명'),
    sa.Column('target_company_id', sa.Integer(), nullable=True, comment='피투자사 기업 ID (식별된 경우)'),
    sa.Column('amount', sa.Numeric(precision=20, scale=0), nullable=True, comment='투자 금액 (원)'),
    sa.Column('amount_display', sa.String(length=50), nullable=True, comment='투자 금액 표시용 (예: 100억원)'),
    sa.Column('round_stage', sa.String(length=30), nullable=True, comment='투자 단계 (seed/series_a/...)'),
    sa.Column('sector', sa.String(length=30), nullable=True, comment='투자 섹터 (ai_deeptech/bio_health/...)'),
    sa.Column('sector_keywords', sa.Text(), nullable=True, comment='섹터 분류 근거 키워드 (JSON)'),
    sa.Column('deal_date', sa.Date(), nullable=True, comment='거래일'),
    sa.Column('deal_year', sa.Integer(), nullable=True, comment='거래 연도 (집계용)'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='출처 URL'),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment='출처 유형 (news/disclosure/manual)'),
    sa.Column('news_article_id', sa.Integer(), nullable=True, comment='원본 뉴스 ID'),
    sa.Column('is_lead_investor', sa.Boolean(), nullable=False, comment='리드 투자사 여부'),
    sa.Column('co_investors', sa.Text(), nullable=True, comment='공동 투자사 목록 (JSON)'),
    sa.Column('description', sa.Text(), nullable=True, comment='딜 설명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_deal_date'), 'deals', ['deal_date'], unique=False)
    op.create_index(op.f('ix_deals_deal_year'), 'deals', ['deal_year'], unique=False)
    op.create_index(op.f('ix_deals_round_stage'), 'deals', ['round_stage'], unique=False)
    op.create_index(op.f('ix_deals_sector'), 'deals', ['sector'], unique=False)
    op.create_index(op.f('ix_deals_target_company'), 'deals', ['target_company'], unique=False)
    op.create_index(op.f('ix_deals_target_company_id'), 'deals', ['target_company_id'], unique=False)
    op.create_table('fund_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(length=100), nullable=False, comment='운용인력 이름'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='직책'),
    sa.Column('role', sa.String(length=100), nullable=True, comment='역할 (펀드매니저/심사역)'),
    sa.Column('career_years', sa.Integer(), nullable=True, comment='경력 년수'),
    sa.Column('education', sa.String(length=200), nullable=True, comment='학력'),
    sa.Column('certifications', sa.Text(), nullable=True, comment='자격증'),
    sa.Column('appointed_date', sa.Date(), nullable=True, comment='임명일'),
    sa.Column('resigned_date', sa.Date(), nullable=True, comment='사임일'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='재직 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_managers_fund_id'), 'fund_managers', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_managers_manager_name'), 'fund_managers', ['manager_name'], unique=False)
    op.create_table('reits_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reits_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=300), nullable=False, comment='자산명'),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment='자산 유형 (office/logistics/residential/retail/hotel/other)'),
    sa.Column('asset_value', sa.Numeric(precision=20, scale=0), nullable=True, comment='자산 가액 (백만원)'),
    sa.Column('asset_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='자산 비율 (%)'),
    sa.Column('location', sa.String(length=300), nullable=True, comment='소재지'),
    sa.Column('acquisition_date', sa.Date(), nullable=True, comment='취득일'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reits_id'], ['reits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reits_assets_reits_id'), 'reits_assets', ['reits_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reits_assets_reits_id'), table_name='reits_assets')
    op.drop_table('reits_assets')
    op.drop_index(op.f('ix_fund_managers_manager_name'), table_name='fund_managers')
    op.drop_index(op.f('ix_fund_managers_fund_id'), table_name='fund_managers')
    op.drop_table('fund_managers')
    op.drop_index(op.f('ix_deals_target_company_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_target_company'), table_name='deals')
    op.drop_index(op.f('ix_deals_sector'), table_name='deals')
    op.drop_index(op.f('ix_deals_round_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_year'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_date'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_reputation_scores_company_id'), table_name='reputation_scores')
    op.drop_table('reputation_scores')
    op.drop_index(op.f('ix_reputation_history_recorded_at'), table_name='reputation_history')
    op.drop_index(op.f('ix_reputation_history_company_id'), table_name='reputation_history')
    op.drop_table('reputation_history')
    op.drop_index(op.f('ix_reits_reits_name'), table_name='reits')
    op.drop_index(op.f('ix_reits_reits_code'), table_name='reits')
    op.drop_index(op.f('ix_reits_company_id'), table_name='reits')
    op.drop_table('reits')
    op.drop_index(op.f('ix_news_articles_url_hash'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_title'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_source'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_company_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_funds_fund_name'), table_name='funds')
    op.drop_index(op.f('ix_funds_fund_code'), table_name='funds')
    op.drop_index(op.f('ix_funds_company_name'), table_name='funds')
    op.drop_index(op.f('ix_funds_company_id'), table_name='funds')
    op.drop_table('funds')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_alias_name'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_companies_stock_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_corp_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_corp_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
