"""한국 산업별 규제 맵.

> 마지막 수정: 2026-02-12 10:39:21

MRFTA, FSCMA, 외국인투자촉진법, 개인정보보호법 등
한국 M&A에 적용되는 규제를 산업별로 정의한다.
"""

from __future__ import annotations

from src.industry.korea.models import RegulatoryItem, Severity

ALL_INDUSTRIES = ["tech", "manufacturing", "healthcare", "logistics", "financial_services"]

REGULATORY_ITEMS: list[RegulatoryItem] = [
    # ── 공통 규제 (4개) ──
    RegulatoryItem(
        regulation_id="mrfta_merger",
        law_name_kr="독점규제 및 공정거래에 관한 법률",
        law_name_en="Monopoly Regulation and Fair Trade Act (MRFTA)",
        authority="공정거래위원회",
        description="일정 규모 이상 기업결합 시 공정위 사전 신고 의무",
        deal_impact="기업결합 신고 지연 시 거래 클로징 불가. 심사 기간 30~120일 소요",
        applicable_industries=ALL_INDUSTRIES,
        severity=Severity.HIGH,
        key_articles=["제11조", "제12조"],
    ),
    RegulatoryItem(
        regulation_id="fscma",
        law_name_kr="자본시장과 금융투자업에 관한 법률",
        law_name_en="Financial Services and Capital Markets Act (FSCMA)",
        authority="금융위원회",
        description="상장법인 M&A 시 공개매수, 대량보유보고 의무",
        deal_impact="5% 이상 지분 취득 시 보고 의무, 공개매수 요건 충족 필요",
        applicable_industries=ALL_INDUSTRIES,
        severity=Severity.HIGH,
        key_articles=["제133조", "제147조"],
    ),
    RegulatoryItem(
        regulation_id="foreign_investment",
        law_name_kr="외국인투자촉진법",
        law_name_en="Foreign Investment Promotion Act (FIPA)",
        authority="산업통상자원부",
        description="외국인 투자자의 국내 기업 투자 시 신고 및 인센티브",
        deal_impact="외국인 투자 비율에 따른 신고/허가 요건, 세제 혜택 가능",
        applicable_industries=ALL_INDUSTRIES,
        severity=Severity.MEDIUM,
        key_articles=["제5조", "제21조"],
    ),
    RegulatoryItem(
        regulation_id="pipa",
        law_name_kr="개인정보 보호법",
        law_name_en="Personal Information Protection Act (PIPA)",
        authority="개인정보보호위원회",
        description="M&A 시 개인정보 이전 및 처리에 관한 규제",
        deal_impact="고객 DB 이전 시 동의 절차 필요, 위반 시 과징금 최대 매출 3%",
        applicable_industries=ALL_INDUSTRIES,
        severity=Severity.HIGH,
        key_articles=["제17조", "제18조", "제75조의2"],
    ),
    # ── Tech 규제 (3개) ──
    RegulatoryItem(
        regulation_id="telecom_business",
        law_name_kr="전기통신사업법",
        law_name_en="Telecommunications Business Act",
        authority="과학기술정보통신부",
        description="기간통신사업자 M&A 시 인가, 부가통신사업 변경 신고",
        deal_impact="기간통신사업 인가 소요 최대 90일, 사업자 변경 신고 필수",
        applicable_industries=["tech"],
        severity=Severity.HIGH,
        key_articles=["제18조", "제22조"],
    ),
    RegulatoryItem(
        regulation_id="ict_network",
        law_name_kr="정보통신망 이용촉진 및 정보보호 등에 관한 법률",
        law_name_en="Act on Promotion of ICT Network Utilization and Information Protection",
        authority="과학기술정보통신부",
        description="정보통신서비스 제공자의 개인정보 보호 및 보안 의무",
        deal_impact="정보보호 관리체계(ISMS) 인증 유지 필요, 침해사고 발생 시 책임 승계",
        applicable_industries=["tech"],
        severity=Severity.MEDIUM,
        key_articles=["제47조", "제47조의3"],
    ),
    RegulatoryItem(
        regulation_id="cloud_computing",
        law_name_kr="클라우드컴퓨팅 발전 및 이용자 보호에 관한 법률",
        law_name_en="Cloud Computing Development Act",
        authority="과학기술정보통신부",
        description="클라우드 서비스 제공자의 이용자 보호 의무",
        deal_impact="클라우드 사업 양수도 시 이용자 통지 및 데이터 이전 의무",
        applicable_industries=["tech"],
        severity=Severity.LOW,
        key_articles=["제25조", "제27조"],
    ),
    # ── Healthcare 규제 (3개) ──
    RegulatoryItem(
        regulation_id="pharmaceutical",
        law_name_kr="약사법",
        law_name_en="Pharmaceutical Affairs Act",
        authority="식품의약품안전처",
        description="의약품 제조·수입업 허가, 변경 시 재허가 절차",
        deal_impact="제조업 허가 승계 절차 필요 (3~6개월), GMP 적합 판정 유지 확인",
        applicable_industries=["healthcare"],
        severity=Severity.HIGH,
        key_articles=["제31조", "제42조"],
    ),
    RegulatoryItem(
        regulation_id="medical_devices",
        law_name_kr="의료기기법",
        law_name_en="Medical Devices Act",
        authority="식품의약품안전처",
        description="의료기기 제조·수입업 허가 및 변경",
        deal_impact="의료기기 품목 허가 승계 절차, 기술문서 이전 확인",
        applicable_industries=["healthcare"],
        severity=Severity.HIGH,
        key_articles=["제6조", "제15조"],
    ),
    RegulatoryItem(
        regulation_id="nhi",
        law_name_kr="국민건강보험법",
        law_name_en="National Health Insurance Act",
        authority="보건복지부",
        description="건강보험 요양기관 지정 및 약가 결정",
        deal_impact="약가 변동 리스크, 요양기관 지정 승계 가능 여부 확인",
        applicable_industries=["healthcare"],
        severity=Severity.MEDIUM,
        key_articles=["제41조", "제46조"],
    ),
    # ── Manufacturing + Logistics 규제 (1개) ──
    RegulatoryItem(
        regulation_id="osha",
        law_name_kr="산업안전보건법",
        law_name_en="Occupational Safety and Health Act",
        authority="고용노동부",
        description="사업장 안전보건 관리, 중대재해 시 처벌 강화",
        deal_impact="중대재해처벌법 적용 대상 여부 확인, 안전관리 비용 반영",
        applicable_industries=["manufacturing", "logistics"],
        severity=Severity.HIGH,
        key_articles=["제38조", "제63조"],
    ),
    # ── Manufacturing 규제 (1개) ──
    RegulatoryItem(
        regulation_id="eia",
        law_name_kr="환경영향평가법",
        law_name_en="Environmental Impact Assessment Act",
        authority="환경부",
        description="일정 규모 이상 사업장 환경영향평가 의무",
        deal_impact="환경 부채(토양 오염, 폐기물) 실사 필수, 환경복원 비용 반영",
        applicable_industries=["manufacturing"],
        severity=Severity.MEDIUM,
        key_articles=["제22조", "제43조"],
    ),
    # ── Financial Services 규제 (3개) ──
    RegulatoryItem(
        regulation_id="banking_act",
        law_name_kr="은행법",
        law_name_en="Banking Act",
        authority="금융위원회",
        description="은행업 인가, 대주주 적격성 심사, 동일인 신용공여 한도",
        deal_impact="은행 지분 10% 이상 취득 시 금융위 사전 승인 필수. 대주주 변경 심사 3~6개월",
        applicable_industries=["financial_services"],
        severity=Severity.HIGH,
        key_articles=["제15조", "제16조의2", "제35조"],
    ),
    RegulatoryItem(
        regulation_id="insurance_business",
        law_name_kr="보험업법",
        law_name_en="Insurance Business Act",
        authority="금융위원회",
        description="보험회사 대주주 변경 승인, 지급여력비율(RBC) 규제",
        deal_impact="보험사 대주주 변경 시 금융위 승인 필요. RBC 150% 이상 유지 의무",
        applicable_industries=["financial_services"],
        severity=Severity.HIGH,
        key_articles=["제10조", "제123조"],
    ),
    RegulatoryItem(
        regulation_id="credit_info",
        law_name_kr="신용정보의 이용 및 보호에 관한 법률",
        law_name_en="Credit Information Use and Protection Act",
        authority="금융위원회",
        description="신용정보 이전·활용 규제, 마이데이터 사업 인허가",
        deal_impact="M&A 시 신용정보 이전 동의 절차 필수, 마이데이터 사업 허가 승계 확인",
        applicable_industries=["financial_services"],
        severity=Severity.MEDIUM,
        key_articles=["제32조", "제33조의2"],
    ),
    # ── Logistics 규제 (2개) ──
    RegulatoryItem(
        regulation_id="freight_transport",
        law_name_kr="화물자동차 운수사업법",
        law_name_en="Freight Truck Transport Business Act",
        authority="국토교통부",
        description="화물운송사업 허가 및 차량 등록",
        deal_impact="운수사업 허가 승계 절차 필수, 차량 대수 변경 신고",
        applicable_industries=["logistics"],
        severity=Severity.HIGH,
        key_articles=["제3조", "제5조"],
    ),
    RegulatoryItem(
        regulation_id="logistics_policy",
        law_name_kr="물류정책기본법",
        law_name_en="Framework Act on Logistics Policies",
        authority="국토교통부",
        description="물류 인프라 개발 및 물류업 등록",
        deal_impact="물류단지 개발 사업 참여 자격, 물류업 등록 유지 확인",
        applicable_industries=["logistics"],
        severity=Severity.LOW,
        key_articles=["제21조", "제29조"],
    ),
]
