"""표준 라인아이템(CoA Canon) v1 시드 데이터 — FDD-301.

80개 표준 라인아이템을 DB에 upsert.
한국 K-IFRS 기준 + FDD 실무에서 자주 사용하는 항목 구성.
"""

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.standard_line_item import (
    FinancialStatement,
    LineItemCategory,
    StandardLineItem,
)

# (code, name_en, name_ko, category, statement_type, display_order, parent_code, is_subtotal, keywords)
_COA_CANON: list[tuple] = [
    # ═══════════════════════════════════════════════════════════
    # Income Statement (IS) — 30 items
    # ═══════════════════════════════════════════════════════════
    # ── Revenue ──
    (
        "IS-REV-001",
        "Revenue",
        "매출액",
        "REVENUE",
        "IS",
        100,
        None,
        False,
        ["매출", "수익", "매출액", "revenue", "sales", "net sales", "turnover"],
    ),
    (
        "IS-REV-002",
        "Product Revenue",
        "제품매출",
        "REVENUE",
        "IS",
        110,
        "IS-REV-001",
        False,
        ["제품매출", "상품매출", "product revenue", "goods sold"],
    ),
    (
        "IS-REV-003",
        "Service Revenue",
        "용역매출",
        "REVENUE",
        "IS",
        120,
        "IS-REV-001",
        False,
        ["용역매출", "서비스매출", "service revenue", "service income"],
    ),
    (
        "IS-REV-004",
        "Other Revenue",
        "기타매출",
        "REVENUE",
        "IS",
        130,
        "IS-REV-001",
        False,
        ["기타매출", "기타수익", "other revenue"],
    ),
    # ── COGS ──
    (
        "IS-COGS-001",
        "Cost of Goods Sold",
        "매출원가",
        "COGS",
        "IS",
        200,
        None,
        False,
        [
            "매출원가",
            "원가",
            "cost of goods",
            "COGS",
            "cost of sales",
            "cost of revenue",
        ],
    ),
    (
        "IS-COGS-002",
        "Material Cost",
        "재료비",
        "COGS",
        "IS",
        210,
        "IS-COGS-001",
        False,
        ["재료비", "원재료비", "material cost", "raw material"],
    ),
    (
        "IS-COGS-003",
        "Labor Cost (COGS)",
        "노무비",
        "COGS",
        "IS",
        220,
        "IS-COGS-001",
        False,
        ["노무비", "인건비(제조)", "labor cost", "direct labor"],
    ),
    (
        "IS-COGS-004",
        "Manufacturing Overhead",
        "제조경비",
        "COGS",
        "IS",
        230,
        "IS-COGS-001",
        False,
        ["제조경비", "제조간접비", "manufacturing overhead", "factory overhead"],
    ),
    (
        "IS-COGS-005",
        "Gross Profit",
        "매출총이익",
        "COGS",
        "IS",
        290,
        None,
        True,
        ["매출총이익", "총이익", "gross profit", "gross margin"],
    ),
    # ── SG&A ──
    (
        "IS-SGA-001",
        "Selling, General & Administrative",
        "판매비와관리비",
        "SGA",
        "IS",
        300,
        None,
        False,
        [
            "판매비",
            "관리비",
            "판매비와관리비",
            "판관비",
            "SGA",
            "selling general",
            "operating expense",
        ],
    ),
    (
        "IS-SGA-002",
        "Salaries & Wages",
        "급여",
        "SGA",
        "IS",
        310,
        "IS-SGA-001",
        False,
        ["급여", "임금", "인건비", "salaries", "wages", "payroll", "compensation"],
    ),
    (
        "IS-SGA-003",
        "Rent Expense",
        "임차료",
        "SGA",
        "IS",
        320,
        "IS-SGA-001",
        False,
        ["임차료", "지급임차료", "rent", "lease expense"],
    ),
    (
        "IS-SGA-004",
        "Insurance Expense",
        "보험료",
        "SGA",
        "IS",
        330,
        "IS-SGA-001",
        False,
        ["보험료", "insurance", "insurance expense"],
    ),
    (
        "IS-SGA-005",
        "Travel & Entertainment",
        "여비교통비",
        "SGA",
        "IS",
        340,
        "IS-SGA-001",
        False,
        ["여비교통비", "접대비", "travel", "entertainment", "business trip"],
    ),
    (
        "IS-SGA-006",
        "Professional Fees",
        "지급수수료",
        "SGA",
        "IS",
        350,
        "IS-SGA-001",
        False,
        [
            "지급수수료",
            "전문가비용",
            "professional fees",
            "consulting fees",
            "advisory",
        ],
    ),
    (
        "IS-SGA-007",
        "Advertising & Marketing",
        "광고선전비",
        "SGA",
        "IS",
        360,
        "IS-SGA-001",
        False,
        ["광고선전비", "마케팅비", "advertising", "marketing", "promotion"],
    ),
    (
        "IS-SGA-008",
        "Bad Debt Expense",
        "대손상각비",
        "SGA",
        "IS",
        370,
        "IS-SGA-001",
        False,
        [
            "대손상각비",
            "대손충당금",
            "bad debt",
            "doubtful accounts",
            "provision for bad debt",
        ],
    ),
    (
        "IS-SGA-009",
        "Other SG&A",
        "기타판관비",
        "SGA",
        "IS",
        380,
        "IS-SGA-001",
        False,
        ["기타판관비", "기타판매비", "other SGA", "other operating"],
    ),
    # ── D&A ──
    (
        "IS-DA-001",
        "Depreciation",
        "감가상각비",
        "DEPRECIATION_AMORTIZATION",
        "IS",
        400,
        None,
        False,
        ["감가상각비", "감가상각", "depreciation"],
    ),
    (
        "IS-DA-002",
        "Amortization",
        "무형자산상각비",
        "DEPRECIATION_AMORTIZATION",
        "IS",
        410,
        None,
        False,
        ["무형자산상각", "상각비", "amortization"],
    ),
    # ── Operating Income ──
    (
        "IS-OOI-001",
        "Other Operating Income",
        "기타영업수익",
        "OTHER_OPERATING_INCOME",
        "IS",
        450,
        None,
        False,
        ["기타영업수익", "영업외수익", "other operating income"],
    ),
    (
        "IS-OOI-002",
        "Other Operating Expense",
        "기타영업비용",
        "OTHER_OPERATING_INCOME",
        "IS",
        460,
        None,
        False,
        ["기타영업비용", "other operating expense"],
    ),
    (
        "IS-OOI-003",
        "Operating Income",
        "영업이익",
        "OTHER_OPERATING_INCOME",
        "IS",
        490,
        None,
        True,
        ["영업이익", "operating income", "operating profit", "EBIT"],
    ),
    # ── Non-Operating ──
    (
        "IS-NON-001",
        "Interest Income",
        "이자수익",
        "INTEREST_INCOME",
        "IS",
        500,
        None,
        False,
        ["이자수익", "수입이자", "interest income", "interest received"],
    ),
    (
        "IS-NON-002",
        "Interest Expense",
        "이자비용",
        "INTEREST_EXPENSE",
        "IS",
        510,
        None,
        False,
        ["이자비용", "지급이자", "interest expense", "finance cost", "borrowing cost"],
    ),
    (
        "IS-NON-003",
        "Foreign Exchange Gain/Loss",
        "외환차손익",
        "NON_OPERATING",
        "IS",
        520,
        None,
        False,
        [
            "외환차손익",
            "외화환산",
            "foreign exchange",
            "FX gain",
            "FX loss",
            "currency",
        ],
    ),
    (
        "IS-NON-004",
        "Other Non-Operating Income",
        "기타영업외수익",
        "NON_OPERATING",
        "IS",
        530,
        None,
        False,
        ["기타영업외수익", "영업외수익", "non-operating income"],
    ),
    (
        "IS-NON-005",
        "Other Non-Operating Expense",
        "기타영업외비용",
        "NON_OPERATING",
        "IS",
        540,
        None,
        False,
        ["기타영업외비용", "영업외비용", "non-operating expense"],
    ),
    # ── Tax ──
    (
        "IS-TAX-001",
        "Income Tax Expense",
        "법인세비용",
        "TAX_EXPENSE",
        "IS",
        600,
        None,
        False,
        [
            "법인세비용",
            "법인세",
            "소득세",
            "income tax",
            "tax expense",
            "corporate tax",
        ],
    ),
    (
        "IS-TAX-002",
        "Net Income",
        "당기순이익",
        "TAX_EXPENSE",
        "IS",
        690,
        None,
        True,
        ["당기순이익", "순이익", "net income", "net profit", "profit for the period"],
    ),
    # ═══════════════════════════════════════════════════════════
    # Balance Sheet (BS) — 50 items
    # ═══════════════════════════════════════════════════════════
    # ── Cash & Cash Equivalents ──
    (
        "BS-CASH-001",
        "Cash & Cash Equivalents",
        "현금및현금성자산",
        "CASH",
        "BS",
        1000,
        None,
        False,
        ["현금", "현금성자산", "현금및현금성자산", "cash", "cash equivalents", "bank"],
    ),
    (
        "BS-CASH-002",
        "Short-term Financial Assets",
        "단기금융상품",
        "CASH",
        "BS",
        1010,
        None,
        False,
        ["단기금융상품", "단기투자", "short-term investments", "time deposits"],
    ),
    (
        "BS-CASH-003",
        "Restricted Cash",
        "사용제한 예금",
        "CASH",
        "BS",
        1020,
        None,
        False,
        ["사용제한", "제한예금", "restricted cash", "pledged deposits"],
    ),
    # ── Accounts Receivable ──
    (
        "BS-AR-001",
        "Accounts Receivable",
        "매출채권",
        "AR",
        "BS",
        1100,
        None,
        False,
        ["매출채권", "외상매출금", "accounts receivable", "trade receivable", "AR"],
    ),
    (
        "BS-AR-002",
        "Allowance for Doubtful Accounts",
        "대손충당금",
        "AR",
        "BS",
        1110,
        "BS-AR-001",
        False,
        ["대손충당금", "충당금", "allowance for doubtful", "bad debt reserve"],
    ),
    (
        "BS-AR-003",
        "Notes Receivable",
        "받을어음",
        "AR",
        "BS",
        1120,
        None,
        False,
        ["받을어음", "notes receivable"],
    ),
    (
        "BS-AR-004",
        "Other Receivables",
        "미수금",
        "AR",
        "BS",
        1130,
        None,
        False,
        ["미수금", "미수수익", "other receivables", "accrued revenue"],
    ),
    # ── Inventory ──
    (
        "BS-INV-001",
        "Inventory",
        "재고자산",
        "INVENTORY",
        "BS",
        1200,
        None,
        False,
        ["재고자산", "재고", "inventory", "stock", "merchandise"],
    ),
    (
        "BS-INV-002",
        "Raw Materials",
        "원재료",
        "INVENTORY",
        "BS",
        1210,
        "BS-INV-001",
        False,
        ["원재료", "raw materials"],
    ),
    (
        "BS-INV-003",
        "Work in Progress",
        "재공품",
        "INVENTORY",
        "BS",
        1220,
        "BS-INV-001",
        False,
        ["재공품", "반제품", "work in progress", "WIP"],
    ),
    (
        "BS-INV-004",
        "Finished Goods",
        "제품",
        "INVENTORY",
        "BS",
        1230,
        "BS-INV-001",
        False,
        ["제품", "상품", "finished goods", "products"],
    ),
    # ── Other Current Assets ──
    (
        "BS-OCA-001",
        "Advance Payments",
        "선급금",
        "OTHER_CURRENT_ASSETS",
        "BS",
        1300,
        None,
        False,
        ["선급금", "advance payments", "prepaid"],
    ),
    (
        "BS-OCA-002",
        "Prepaid Expenses",
        "선급비용",
        "OTHER_CURRENT_ASSETS",
        "BS",
        1310,
        None,
        False,
        ["선급비용", "prepaid expenses"],
    ),
    (
        "BS-OCA-003",
        "VAT Receivable",
        "부가세대급금",
        "OTHER_CURRENT_ASSETS",
        "BS",
        1320,
        None,
        False,
        ["부가세대급금", "부가세", "VAT receivable", "input VAT"],
    ),
    (
        "BS-OCA-004",
        "Other Current Assets",
        "기타유동자산",
        "OTHER_CURRENT_ASSETS",
        "BS",
        1390,
        None,
        False,
        ["기타유동자산", "other current assets"],
    ),
    # ── PPE ──
    (
        "BS-PPE-001",
        "Property, Plant & Equipment",
        "유형자산",
        "PPE",
        "BS",
        1400,
        None,
        False,
        ["유형자산", "고정자산", "PPE", "property plant equipment", "tangible assets"],
    ),
    (
        "BS-PPE-002",
        "Land",
        "토지",
        "PPE",
        "BS",
        1410,
        "BS-PPE-001",
        False,
        ["토지", "land"],
    ),
    (
        "BS-PPE-003",
        "Buildings",
        "건물",
        "PPE",
        "BS",
        1420,
        "BS-PPE-001",
        False,
        ["건물", "건축물", "buildings", "structures"],
    ),
    (
        "BS-PPE-004",
        "Machinery & Equipment",
        "기계장치",
        "PPE",
        "BS",
        1430,
        "BS-PPE-001",
        False,
        ["기계장치", "기계", "machinery", "equipment"],
    ),
    (
        "BS-PPE-005",
        "Vehicles",
        "차량운반구",
        "PPE",
        "BS",
        1440,
        "BS-PPE-001",
        False,
        ["차량운반구", "차량", "vehicles", "automobiles"],
    ),
    (
        "BS-PPE-006",
        "Office Equipment",
        "비품",
        "PPE",
        "BS",
        1450,
        "BS-PPE-001",
        False,
        ["비품", "사무용품", "office equipment", "furniture", "fixtures"],
    ),
    (
        "BS-PPE-007",
        "Construction in Progress",
        "건설중인자산",
        "PPE",
        "BS",
        1460,
        "BS-PPE-001",
        False,
        ["건설중인자산", "construction in progress", "CIP"],
    ),
    (
        "BS-PPE-008",
        "Accumulated Depreciation (PPE)",
        "감가상각누계액",
        "PPE",
        "BS",
        1470,
        "BS-PPE-001",
        False,
        ["감가상각누계액", "상각누계", "accumulated depreciation"],
    ),
    (
        "BS-PPE-009",
        "Right-of-Use Assets",
        "사용권자산",
        "PPE",
        "BS",
        1480,
        None,
        False,
        ["사용권자산", "리스자산", "right-of-use", "ROU asset", "IFRS 16"],
    ),
    # ── Intangibles ──
    (
        "BS-INT-001",
        "Intangible Assets",
        "무형자산",
        "INTANGIBLES",
        "BS",
        1500,
        None,
        False,
        ["무형자산", "intangible assets"],
    ),
    (
        "BS-INT-002",
        "Goodwill",
        "영업권",
        "INTANGIBLES",
        "BS",
        1510,
        "BS-INT-001",
        False,
        ["영업권", "goodwill"],
    ),
    (
        "BS-INT-003",
        "Software",
        "소프트웨어",
        "INTANGIBLES",
        "BS",
        1520,
        "BS-INT-001",
        False,
        ["소프트웨어", "software", "개발비"],
    ),
    (
        "BS-INT-004",
        "Patents & Trademarks",
        "산업재산권",
        "INTANGIBLES",
        "BS",
        1530,
        "BS-INT-001",
        False,
        ["산업재산권", "특허", "상표", "patents", "trademarks", "IP"],
    ),
    (
        "BS-INT-005",
        "Other Intangible Assets",
        "기타무형자산",
        "INTANGIBLES",
        "BS",
        1540,
        "BS-INT-001",
        False,
        ["기타무형자산", "other intangible"],
    ),
    # ── Other Non-Current Assets ──
    (
        "BS-ONCA-001",
        "Long-term Financial Assets",
        "장기금융상품",
        "OTHER_NONCURRENT_ASSETS",
        "BS",
        1600,
        None,
        False,
        ["장기금융상품", "장기투자", "long-term investments"],
    ),
    (
        "BS-ONCA-002",
        "Long-term Receivables",
        "장기미수금",
        "OTHER_NONCURRENT_ASSETS",
        "BS",
        1610,
        None,
        False,
        ["장기미수금", "장기대여금", "long-term receivables", "long-term loans"],
    ),
    (
        "BS-ONCA-003",
        "Deferred Tax Assets",
        "이연법인세자산",
        "OTHER_NONCURRENT_ASSETS",
        "BS",
        1620,
        None,
        False,
        ["이연법인세자산", "이연세금자산", "deferred tax asset", "DTA"],
    ),
    (
        "BS-ONCA-004",
        "Other Non-Current Assets",
        "기타비유동자산",
        "OTHER_NONCURRENT_ASSETS",
        "BS",
        1690,
        None,
        False,
        ["기타비유동자산", "other non-current assets"],
    ),
    # ── Accounts Payable ──
    (
        "BS-AP-001",
        "Accounts Payable",
        "매입채무",
        "AP",
        "BS",
        2000,
        None,
        False,
        ["매입채무", "외상매입금", "accounts payable", "trade payable", "AP"],
    ),
    (
        "BS-AP-002",
        "Notes Payable",
        "지급어음",
        "AP",
        "BS",
        2010,
        None,
        False,
        ["지급어음", "notes payable"],
    ),
    # ── Accruals ──
    (
        "BS-ACC-001",
        "Accrued Expenses",
        "미지급비용",
        "ACCRUALS",
        "BS",
        2100,
        None,
        False,
        ["미지급비용", "미지급금", "accrued expenses", "accrued liabilities"],
    ),
    (
        "BS-ACC-002",
        "Accrued Salaries",
        "미지급급여",
        "ACCRUALS",
        "BS",
        2110,
        "BS-ACC-001",
        False,
        ["미지급급여", "미지급임금", "accrued salaries", "accrued wages"],
    ),
    (
        "BS-ACC-003",
        "Accrued Tax",
        "미지급법인세",
        "ACCRUALS",
        "BS",
        2120,
        "BS-ACC-001",
        False,
        ["미지급법인세", "미지급세금", "accrued tax", "tax payable"],
    ),
    (
        "BS-ACC-004",
        "Advance from Customers",
        "선수금",
        "ACCRUALS",
        "BS",
        2130,
        None,
        False,
        [
            "선수금",
            "선수수익",
            "advance from customers",
            "customer deposits",
            "deferred revenue",
        ],
    ),
    (
        "BS-ACC-005",
        "Provision for Warranty",
        "판매보증충당부채",
        "ACCRUALS",
        "BS",
        2140,
        None,
        False,
        [
            "판매보증충당부채",
            "보증충당",
            "warranty provision",
            "provision for warranty",
        ],
    ),
    # ── Other Current Liabilities ──
    (
        "BS-OCL-001",
        "VAT Payable",
        "부가세예수금",
        "OTHER_CURRENT_LIABILITIES",
        "BS",
        2200,
        None,
        False,
        ["부가세예수금", "부가세", "VAT payable", "output VAT"],
    ),
    (
        "BS-OCL-002",
        "Withholding Tax Payable",
        "예수금",
        "OTHER_CURRENT_LIABILITIES",
        "BS",
        2210,
        None,
        False,
        ["예수금", "원천세", "withholding tax", "payroll tax"],
    ),
    (
        "BS-OCL-003",
        "Current Portion of Long-term Debt",
        "유동성장기부채",
        "OTHER_CURRENT_LIABILITIES",
        "BS",
        2220,
        None,
        False,
        ["유동성장기부채", "장기차입금유동", "current portion", "CPLTD"],
    ),
    (
        "BS-OCL-004",
        "Other Current Liabilities",
        "기타유동부채",
        "OTHER_CURRENT_LIABILITIES",
        "BS",
        2290,
        None,
        False,
        ["기타유동부채", "other current liabilities"],
    ),
    # ── Debt ──
    (
        "BS-DEBT-001",
        "Short-term Borrowings",
        "단기차입금",
        "DEBT",
        "BS",
        2300,
        None,
        False,
        ["단기차입금", "short-term borrowings", "short-term loans", "bank loan"],
    ),
    (
        "BS-DEBT-002",
        "Long-term Borrowings",
        "장기차입금",
        "DEBT",
        "BS",
        2310,
        None,
        False,
        ["장기차입금", "long-term borrowings", "long-term loans", "term loan"],
    ),
    (
        "BS-DEBT-003",
        "Bonds Payable",
        "사채",
        "DEBT",
        "BS",
        2320,
        None,
        False,
        ["사채", "회사채", "bonds payable", "corporate bonds"],
    ),
    (
        "BS-DEBT-004",
        "Convertible Bonds",
        "전환사채",
        "DEBT",
        "BS",
        2330,
        None,
        False,
        ["전환사채", "CB", "convertible bonds"],
    ),
    # ── Lease Liabilities ──
    (
        "BS-LEASE-001",
        "Lease Liabilities (Current)",
        "리스부채(유동)",
        "LEASE_LIABILITIES",
        "BS",
        2400,
        None,
        False,
        ["리스부채", "유동리스", "lease liabilities current", "IFRS 16 current"],
    ),
    (
        "BS-LEASE-002",
        "Lease Liabilities (Non-Current)",
        "리스부채(비유동)",
        "LEASE_LIABILITIES",
        "BS",
        2410,
        None,
        False,
        [
            "장기리스부채",
            "비유동리스",
            "lease liabilities non-current",
            "IFRS 16 non-current",
        ],
    ),
    # ── Other Non-Current Liabilities ──
    (
        "BS-ONCL-001",
        "Retirement Benefit Obligations",
        "퇴직급여충당부채",
        "OTHER_NONCURRENT_LIABILITIES",
        "BS",
        2500,
        None,
        False,
        [
            "퇴직급여충당",
            "퇴직금",
            "retirement benefit",
            "pension obligation",
            "severance",
        ],
    ),
    (
        "BS-ONCL-002",
        "Deferred Tax Liabilities",
        "이연법인세부채",
        "OTHER_NONCURRENT_LIABILITIES",
        "BS",
        2510,
        None,
        False,
        ["이연법인세부채", "이연세금부채", "deferred tax liability", "DTL"],
    ),
    (
        "BS-ONCL-003",
        "Other Non-Current Liabilities",
        "기타비유동부채",
        "OTHER_NONCURRENT_LIABILITIES",
        "BS",
        2590,
        None,
        False,
        ["기타비유동부채", "기타장기부채", "other non-current liabilities"],
    ),
    # ── Equity ──
    (
        "BS-EQ-001",
        "Share Capital",
        "자본금",
        "EQUITY",
        "BS",
        3000,
        None,
        False,
        ["자본금", "주식", "share capital", "common stock", "paid-in capital"],
    ),
    (
        "BS-EQ-002",
        "Capital Surplus",
        "자본잉여금",
        "EQUITY",
        "BS",
        3010,
        None,
        False,
        [
            "자본잉여금",
            "주식발행초과금",
            "capital surplus",
            "additional paid-in capital",
            "APIC",
        ],
    ),
    (
        "BS-EQ-003",
        "Retained Earnings",
        "이익잉여금",
        "EQUITY",
        "BS",
        3020,
        None,
        False,
        ["이익잉여금", "유보이익", "retained earnings", "accumulated profit"],
    ),
    (
        "BS-EQ-004",
        "Other Capital Adjustments",
        "기타자본항목",
        "EQUITY",
        "BS",
        3030,
        None,
        False,
        ["기타자본항목", "기타자본", "other capital", "treasury stock", "자기주식"],
    ),
    (
        "BS-EQ-005",
        "Accumulated Other Comprehensive Income",
        "기타포괄손익누계액",
        "EQUITY",
        "BS",
        3040,
        None,
        False,
        ["기타포괄손익누계", "AOCI", "accumulated other comprehensive income", "OCI"],
    ),
]


def seed_standard_line_items(db: Session) -> int:
    """표준 라인아이템 80개를 DB에 upsert한다.

    Returns:
        생성/갱신된 행 수.
    """
    count = 0
    for row in _COA_CANON:
        code = row[0]
        existing = db.scalar(
            select(StandardLineItem).where(StandardLineItem.code == code)
        )
        if existing:
            existing.name_en = row[1]
            existing.name_ko = row[2]
            existing.category = LineItemCategory(row[3])
            existing.statement_type = FinancialStatement(row[4])
            existing.display_order = row[5]
            existing.parent_code = row[6]
            existing.is_subtotal = row[7]
            existing.keywords = row[8]
        else:
            item = StandardLineItem(
                code=row[0],
                name_en=row[1],
                name_ko=row[2],
                category=LineItemCategory(row[3]),
                statement_type=FinancialStatement(row[4]),
                display_order=row[5],
                parent_code=row[6],
                is_subtotal=row[7],
                keywords=row[8],
            )
            db.add(item)
        count += 1

    db.commit()
    return count
